import type * as all from "./index";

export type SchemaOrg =
  | all.SchoolDistrict
  | all.Bridge
  | all.PublicToilet
  | all.EventAttendanceModeEnumerationEnum
  | all.UserBlocks
  | all.MedicalImagingTechniqueEnum
  | all.Invoice
  | all.DefinedRegion
  | all.PerformAction
  | all.OfficeEquipmentStore
  | all.ReturnFeesEnumerationEnum
  | all.ScheduleAction
  | all.ShippingDeliveryTime
  | all.SizeGroupEnumeration
  | all.ActivateAction
  | all.DrugCostCategoryEnum
  | all.HowToSection
  | string
  | string
  | all.CurrencyConversionService
  | all.Hostel
  | all.Sculpture
  | all.Duration
  | all.Event
  | all.ReplaceAction
  | all.HousePainter
  | all.NonprofitType
  | all.TechArticle
  | all.TransferAction
  | all.TravelAction
  | all.Restaurant
  | all.ImageObjectSnapshot
  | all.MeasurementTypeEnumeration
  | all.Patient
  | all.ScholarlyArticle
  | all.BroadcastService
  | all.IPTCDigitalSourceEnumerationEnum
  | all.OccupationalTherapy
  | all.Embassy
  | all.HairSalon
  | all.HowToSupply
  | string
  | all.GasStation
  | all.CoverArt
  | all.ThreeDModel
  | all.SolveMathAction
  | all.Quotation
  | all.Legislation
  | all.RadioClip
  | all.RepaymentSpecification
  | all.Table
  | all.MediaSubscription
  | all.BankOrCreditUnion
  | all.Dataset
  | all.LodgingBusiness
  | all.MedicalSpecialtyEnum
  | all.LakeBodyOfWater
  | all.MerchantReturnPolicy
  | all.Blog
  | all.Pharmacy
  | all.SubscribeAction
  | all.CatholicChurch
  | all.MusicPlaylist
  | all.SearchResultsPage
  | all.NightClub
  | all.CourseInstance
  | all.SizeSystemEnumerationEnum
  | all.PostalAddress
  | all.Mosque
  | all.MusicVideoObject
  | all.OrderAction
  | all.EnergyEfficiencyEnumeration
  | all.EmergencyService
  | all.Project
  | all.AssessAction
  | all.EnergyStarEnergyEfficiencyEnumerationEnum
  | all.HowTo
  | all.CookAction
  | all.PostalCodeRangeSpecification
  | all.Playground
  | all.CreditCard
  | all.MediaReview
  | all.Vein
  | all.NoteDigitalDocument
  | all.VideoObject
  | all.ExchangeRateSpecification
  | all.GeoShape
  | all.Nerve
  | all.Country
  | all.PathologyTest
  | all.PaymentStatusTypeEnum
  | all.AggregateOffer
  | all.Hackathon
  | all.OfferShippingDetails
  | all.Manuscript
  | all.AgreeAction
  | all.Class
  | all.MensClothingStore
  | all.DownloadAction
  | all.AggregateRating
  | all.APIReference
  | all.CompoundPriceSpecification
  | all.Quantity
  | all.FinancialIncentive
  | all.MemberProgram
  | all.MedicalOrganization
  | all.Conversation
  | all.DepositAccount
  | all.ClothingStore
  | all.Enumeration
  | all.EventReservation
  | all.VideoObjectSnapshot
  | all.OceanBodyOfWater
  | all.Motel
  | all.CancelAction
  | all.Residence
  | all.BarOrPub
  | all.DataFeed
  | all.LinkRole
  | all.TreatmentIndication
  | all.MediaEnumeration
  | all.InsuranceAgency
  | all.BlogPosting
  | all.AutoBodyShop
  | all.DryCleaningOrLaundry
  | all.LiteraryEvent
  | all.TheaterGroup
  | all.ReturnAction
  | all.Occupation
  | all.QuantitativeValueDistribution
  | all.DeactivateAction
  | all.Barcode
  | all.StatisticalPopulation
  | string
  | all.MeasurementMethodEnumEnum
  | all.Recommendation
  | all.ShortStory
  | all.FundingAgency
  | all.OnDemandEvent
  | all.CDCPMDRecord
  | all.IncentiveStatusEnum
  | all.SearchRescueOrganization
  | all.TaxiReservation
  | all.ArchiveOrganization
  | all.SurgicalProcedure
  | all.MedicalTrial
  | all.Demand
  | all.BefriendAction
  | all.BloodTest
  | all.DonateAction
  | all.Action
  | all.UserDownloads
  | all.TrainTrip
  | all.City
  | all.MediaManipulationRatingEnumerationEnum
  | all.Role
  | all.GiveAction
  | all.Locksmith
  | all.MedicalBusiness
  | all.DrugLegalStatus
  | all.EducationEvent
  | all.AdvertiserContentArticle
  | all.MeetingRoom
  | all.PoliceStation
  | all.UserInteraction
  | all.PoliticalParty
  | all.Thesis
  | all.HowToItem
  | all.ExercisePlan
  | all.EngineSpecification
  | all.PlaceOfWorship
  | all.WriteAction
  | all.Continent
  | all.PropertyValue
  | all.ConfirmAction
  | all.Church
  | all.Thing
  | all.BusinessAudience
  | all.Zoo
  | string
  | all.Preschool
  | all.TouristDestination
  | all.RecommendedDoseSchedule
  | all.AccountingService
  | all.SportsClub
  | all.BroadcastFrequencySpecification
  | all.MortgageLoan
  | all.TextDigitalDocument
  | all.DefenceEstablishment
  | all.ReplyAction
  | all.StatusEnumeration
  | all.SiteNavigationElement
  | all.BankAccount
  | all.CollectionPage
  | all.FoodService
  | all.MaximumDoseSchedule
  | all.DeliveryEvent
  | all.PawnShop
  | number
  | all.Library
  | all.BackgroundNewsArticle
  | all.FMRadioChannel
  | all.MusicRelease
  | all.Article
  | all.GroceryStore
  | all.BowlingAlley
  | all.MapCategoryTypeEnum
  | all.HealthInsurancePlan
  | all.MedicalEnumeration
  | all.SkiResort
  | all.CovidTestingFacility
  | all.AskAction
  | all.Drawing
  | all.Mass
  | all.Permit
  | all.EmployerAggregateRating
  | all.IgnoreAction
  | string
  | all.PaymentService
  | all.GameServer
  | all.ComedyEvent
  | all.AudioObjectSnapshot
  | all.Festival
  | all.OrderStatusEnum
  | all.DiagnosticProcedure
  | all.ShareAction
  | all.TVSeason
  | all.BrainStructure
  | all.ShippingConditions
  | all.TherapeuticProcedure
  | all.OutletStore
  | all.EmploymentAgency
  | all.FurnitureStore
  | all.TattooParlor
  | all.DatedMoneySpecification
  | all.SeekToAction
  | all.PalliativeProcedure
  | all.EmployeeRole
  | all.PaymentMethod
  | all.InviteAction
  | all.JewelryStore
  | all.OfferForLease
  | all.InternetCafe
  | all.MedicalGuidelineRecommendation
  | all.MedicalSignOrSymptom
  | all.ResearchOrganization
  | all.UserReview
  | all.AnalysisNewsArticle
  | all.FilmAction
  | all.AutoDealer
  | all.Canal
  | all.MedicalRiskScore
  | all.EventStatusTypeEnum
  | all.HealthClub
  | all.QuantitativeValue
  | all.ToyStore
  | all.ReportageNewsArticle
  | all.MemberProgramTier
  | all.FireStation
  | all.WebContent
  | all.LendAction
  | all.TVSeries
  | all.Course
  | all.MonetaryAmountDistribution
  | all.BioChemEntity
  | all.ReservationStatusTypeEnum
  | all.AddAction
  | all.ElementarySchool
  | all.LiquorStore
  | all.CriticReview
  | all.Question
  | all.SearchAction
  | all.AutoRental
  | all.Quiz
  | all.FulfillmentTypeEnumerationEnum
  | all.RegisterAction
  | all.Distillery
  | all.HealthPlanFormulary
  | all.PresentationDigitalDocument
  | all.VideoGame
  | all.MedicineSystemEnum
  | all.GeospatialGeometry
  | all.Car
  | all.ReservationPackage
  | all.WearableSizeSystemEnumerationEnum
  | all.PhysicalTherapy
  | all.NailSalon
  | all.MusicReleaseFormatTypeEnum
  | all.PublicationEvent
  | all.HowToDirection
  | all.TouristAttraction
  | all.FoodEstablishment
  | all.ConsumeAction
  | all.Game
  | all.AdultEntertainment
  | all.RiverBodyOfWater
  | all.WorkBasedProgram
  | all.HowToTool
  | all.SportsEvent
  | all.FollowAction
  | all.MonetaryGrant
  | all.AllocateAction
  | all.LandmarksOrHistoricalBuildings
  | all.BoardingPolicyTypeEnum
  | all.CheckInAction
  | all.SizeSpecification
  | all.UserTweets
  | all.AutomatedTeller
  | all.TouristInformationCenter
  | all.EmailMessage
  | all.AMRadioChannel
  | all.GeoCircle
  | all.GovernmentBenefitsTypeEnum
  | all.Newspaper
  | all.CorrectionComment
  | all.PetStore
  | all.Property
  | all.WantAction
  | all.TheaterEvent
  | all.Reservation
  | all.InvestmentFund
  | all.TakeAction
  | all.MedicalIndication
  | all.GenderTypeEnum
  | all.LegalValueLevelEnum
  | all.MedicalRiskEstimator
  | all.MarryAction
  | all.MusicAlbum
  | all.MonetaryAmount
  | all.ConvenienceStore
  | all.DigitalDocumentPermission
  | all.GovernmentService
  | all.ItemListOrderTypeEnum
  | all.DataDownload
  | all.RoofingContractor
  | all.Florist
  | all.QualitativeValue
  | all.AutomotiveBusiness
  | all.ApprovedIndication
  | all.BookSeries
  | all.ComicStory
  | all.RentalCarReservation
  | all.DiscussionForumPosting
  | all.LoanOrCredit
  | all.AboutPage
  | all.Season
  | all.Artery
  | all.PlayAction
  | all.MedicalDevice
  | all.Atlas
  | all.LegalForceStatusEnum
  | all.MedicalGuidelineContraindication
  | all.Distance
  | all.Clip
  | all.RadioBroadcastService
  | all.CampingPitch
  | all.BreadcrumbList
  | all.Beach
  | all.WebSite
  | all.InteractionCounter
  | all.AutoPartsStore
  | all.WebPageElement
  | all.QuoteAction
  | all.UseAction
  | all.SportingGoodsStore
  | all.Notary
  | all.Dentist
  | all.MediaObject
  | all.Painting
  | all.ViewAction
  | all.MedicalRiskFactor
  | all.MoneyTransfer
  | all.HealthPlanNetwork
  | all.MediaGallery
  | all.DeleteAction
  | all.ProductCollection
  | all.LodgingReservation
  | all.AutoRepair
  | all.ElectronicsStore
  | all.Suite
  | all.BikeStore
  | all.PriceTypeEnumerationEnum
  | all.SeaBodyOfWater
  | all.AlignmentObject
  | all.BookmarkAction
  | all.Accommodation
  | all.BookStore
  | all.SellAction
  | string
  | all.PodcastEpisode
  | all.DrugCost
  | all.Audiobook
  | all.EducationalOrganization
  | all.BorrowAction
  | all.OrganizeAction
  | all.GamePlayModeEnum
  | all.ImageGallery
  | all.MedicalStudy
  | all.BedAndBreakfast
  | all.AdministrativeArea
  | all.AnatomicalSystem
  | all.GeneralContractor
  | all.DrugPrescriptionStatusEnum
  | all.WarrantyPromise
  | all.RealEstateAgent
  | all.MenuItem
  | all.WPSideBar
  | all.SelfStorage
  | all.SoftwareApplication
  | all.WearAction
  | all.Motorcycle
  | all.SpreadsheetDigitalDocument
  | all.DataFeedItem
  | all.SportsOrganization
  | all.DrugClass
  | all.PhysicalActivityCategoryEnum
  | all.ReceiveAction
  | all.ParcelDelivery
  | all.BoatTrip
  | all.InstallAction
  | all.Claim
  | all.Taxi
  | all.Brewery
  | all.OnlineStore
  | all.MedicalEntity
  | all.CreativeWork
  | all.LibrarySystem
  | all.DietarySupplement
  | all.AudioObject
  | all.RVPark
  | all.Pond
  | all.InfectiousDisease
  | all.Ligament
  | all.Resort
  | all.PublicationIssue
  | all.ArchiveComponent
  | all.EntryPoint
  | all.DataCatalog
  | string
  | all.ChemicalSubstance
  | all.DanceEvent
  | all.Play
  | all.LoseAction
  | all.IndividualPhysician
  | all.Hospital
  | all.Vessel
  | all.SteeringPositionValueEnum
  | all.Specialty
  | all.BedType
  | all.PerformingGroup
  | all.SingleFamilyResidence
  | all.MovingCompany
  | all.PhotographAction
  | all.StadiumOrArena
  | all.BuddhistTemple
  | all.TravelAgency
  | all.MenuSection
  | all.PropertyValueSpecification
  | all.CivicStructure
  | all.Joint
  | all.MedicalProcedureTypeEnum
  | all.Substance
  | all.StatisticalVariable
  | all.Synagogue
  | all.MedicalTrialDesignEnum
  | all.MusicAlbumProductionTypeEnum
  | all.EndorseAction
  | all.Airport
  | all.Product
  | all.ListItem
  | all.ComputerStore
  | all.LymphaticVessel
  | all.MusicStore
  | all.EmployerReview
  | all.BeautySalon
  | all.Physician
  | all.EndorsementRating
  | all.LegislativeBuilding
  | all.MoveAction
  | all.IncentiveQualifiedExpenseTypeEnum
  | all.Gene
  | all.MedicalCause
  | number
  | all.WholesaleStore
  | all.ProductGroup
  | all.SocialMediaPosting
  | all.OfferItemConditionEnum
  | all.ExhibitionEvent
  | all.RsvpResponseTypeEnum
  | all.VisualArtwork
  | all.Seat
  | all.Audience
  | all.MedicalProcedure
  | all.MedicalWebPage
  | all.FastFoodRestaurant
  | all.DrugStrength
  | all.Answer
  | all.MedicalAudienceTypeEnum
  | all.Corporation
  | all.ProgramMembership
  | all.Landform
  | all.VeterinaryCare
  | all.Waterfall
  | all.MusicAlbumReleaseTypeEnum
  | all.PreventionIndication
  | all.TrackAction
  | all.WinAction
  | all.House
  | all.RealEstateListing
  | all.MedicalObservationalStudyDesignEnum
  | all.ParkingFacility
  | all.ItemPage
  | all.WearableSizeGroupEnumerationEnum
  | all.ComicSeries
  | all.MedicalIntangible
  | all.ContactPoint
  | all.NewsArticle
  | all.LearningResource
  | all.SportsTeam
  | all.CategoryCodeSet
  | all.WebApplication
  | all.GovernmentPermit
  | all.Schedule
  | all.Periodical
  | all.ReturnLabelSourceEnumerationEnum
  | all.FoodEvent
  | all.FinancialProduct
  | all.ExerciseAction
  | all.PublicSwimmingPool
  | all.GeoCoordinates
  | all.MusicEvent
  | all.SaleEvent
  | all.MusicRecording
  | all.HowToTip
  | all.ConstraintNode
  | all.ComicCoverArt
  | all.PaymentChargeSpecification
  | all.MotorcycleRepair
  | all.CheckoutPage
  | all.TrainStation
  | all.ArtGallery
  | all.Offer
  | all.RestrictedDietEnum
  | all.PsychologicalTreatment
  | all.ShoppingCenter
  | all.MedicalSymptom
  | all.WebPage
  | all.HyperTocEntry
  | all.HealthAndBeautyBusiness
  | all.WebAPI
  | all.Reservoir
  | all.OrganizationRole
  | all.IncentiveTypeEnum
  | all.TierBenefitEnumerationEnum
  | all.Park
  | all.Language
  | all.Statement
  | all.LegalService
  | all.WPAdBlock
  | all.Intangible
  | all.CompleteDataFeed
  | all.Store
  | all.OrderItem
  | all.BroadcastEvent
  | all.Book
  | all.ClaimReview
  | all.AmusementPark
  | all.RentAction
  | all.HealthAspectEnumerationEnum
  | all.CreateAction
  | all.DanceGroup
  | all.HinduTemple
  | all.MedicalClinic
  | all.Campground
  | all.MedicalStudyStatusEnum
  | all.CableOrSatelliteService
  | all.SportsActivityLocation
  | all.Courthouse
  | all.ProductModel
  | all.AchieveAction
  | all.Energy
  | all.BusinessFunction
  | all.PronounceableText
  | all.IndividualProduct
  | all.Series
  | all.CertificationStatusEnumerationEnum
  | all.OwnershipInfo
  | all.School
  | all.AdultOrientedEnumerationEnum
  | all.MotorizedBicycle
  | all.ComputerLanguage
  | all.State
  | all.BusOrCoach
  | all.Review
  | all.CarUsageTypeEnum
  | all.UnitPriceSpecification
  | all.ListenAction
  | all.UserCheckins
  | all.PaymentCard
  | all.MusicVenue
  | all.MedicalCondition
  | all.ExerciseGym
  | all.AnimalShelter
  | all.FlightReservation
  | all.TelevisionChannel
  | all.AnatomicalStructure
  | all.DeliveryMethodEnum
  | all.CheckAction
  | all.USNonprofitTypeEnum
  | all.Chapter
  | all.UserPlays
  | all.ReportedDoseSchedule
  | all.EventSeries
  | all.QAPage
  | all.HomeGoodsStore
  | all.MerchantReturnPolicySeasonalOverride
  | all.VideoGameSeries
  | all.Consortium
  | all.PriceSpecification
  | all.MedicalTest
  | all.SpeakableSpecification
  | all.TireShop
  | all.AskPublicNewsArticle
  | all.Menu
  | all.InformAction
  | all.VideoGallery
  | all.PreOrderAction
  | all.FloorPlan
  | all.ParentAudience
  | all.DDxElement
  | all.SubwayStation
  | all.SpecialAnnouncement
  | all.WorkersUnion
  | all.ArriveAction
  | all.Collection
  | all.DeliveryChargeSpecification
  | string
  | all.Brand
  | all.FindAction
  | all.ActionStatusTypeEnum
  | all.Certification
  | all.Casino
  | all.ReserveAction
  | all.RadiationTherapy
  | all.DigitalDocument
  | all.ReactAction
  | all.LocalBusiness
  | all.UserPageVisits
  | all.EducationalOccupationalProgram
  | all.DayOfWeekEnum
  | all.ScreeningEvent
  | all.Message
  | all.PrependAction
  | all.OfferCatalog
  | all.InfectiousAgentClassEnum
  | all.EducationalAudience
  | all.NewsMediaOrganization
  | all.MedicalRiskCalculator
  | all.Mountain
  | all.DefinedTermSet
  | all.ReturnMethodEnumerationEnum
  | all.Aquarium
  | all.ChooseAction
  | all.TradeAction
  | all.Protein
  | all.GameServerStatusEnum
  | all.UserLikes
  | all.TelevisionStation
  | all.GardenStore
  | all.TVClip
  | all.MedicalObservationalStudy
  | all.ImagingTest
  | all.MovieSeries
  | all.VacationRental
  | all.WPHeader
  | all.RadioStation
  | all.AssignAction
  | all.HealthPlanCostSharingSpecification
  | all.Guide
  | all.Apartment
  | all.MerchantReturnEnumerationEnum
  | all.CheckOutAction
  | all.CommentAction
  | all.RsvpAction
  | all.RadioEpisode
  | all.JobPosting
  | all.VoteAction
  | all.WearableMeasurementTypeEnumerationEnum
  | all.DiscoverAction
  | all.IceCreamShop
  | all.ImageObject
  | all.SomeProducts
  | all.ShippingRateSettings
  | all.ServicePeriod
  | all.AcceptAction
  | all.EducationalOccupationalCredential
  | all.BodyMeasurementTypeEnumerationEnum
  | all.WarrantyScope
  | all.ItemAvailabilityEnum
  | all.UKNonprofitTypeEnum
  | all.Map
  | all.BrokerageAccount
  | all.MedicalTestPanel
  | all.CafeOrCoffeeShop
  | all.ComedyClub
  | all.PodcastSeason
  | all.ReadAction
  | all.Bakery
  | all.VideoGameClip
  | all.UserComments
  | all.MovieClip
  | all.Ticket
  | all.BedDetails
  | all.EUEnergyEfficiencyEnumerationEnum
  | all.LikeAction
  | all.HowToStep
  | all.Episode
  | all.Room
  | all.AutoWash
  | all.Photograph
  | all.SocialEvent
  | all.Taxon
  | all.BroadcastChannel
  | all.Researcher
  | all.ContactPage
  | all.NutritionInformation
  | all.GolfCourse
  | all.ComicIssue
  | all.TaxiService
  | all.MotorcycleDealer
  | all.Attorney
  | all.DepartmentStore
  | all.MusicGroup
  | all.MusicComposition
  | all.ControlAction
  | all.ResumeAction
  | all.Crematorium
  | all.PeopleAudience
  | all.DrinkAction
  | all.DepartAction
  | all.Code
  | all.SoftwareSourceCode
  | all.HVACBusiness
  | all.Trip
  | all.Museum
  | all.PayAction
  | all.VitalSign
  | all.RefundTypeEnumerationEnum
  | all.VirtualLocation
  | all.MathSolver
  | all.PlanAction
  | all.InvestmentOrDeposit
  | all.BusTrip
  | all.LifestyleModification
  | all.AppendAction
  | all.DigitalDocumentPermissionTypeEnum
  | all.InsertAction
  | all.PodcastSeries
  | all.UserPlusOnes
  | all.LeaveAction
  | all.GovernmentBuilding
  | all.NLNonprofitTypeEnum
  | all.Place
  | all.Grant
  | all.ServiceChannel
  | all.WPFooter
  | all.Vehicle
  | all.Muscle
  | all.TypeAndQuantityNode
  | all.FAQPage
  | all.PhysicalExamEnum
  | all.BusReservation
  | all.BusinessEntityType
  | all.PhysicalActivity
  | all.MobileApplication
  | all.Electrician
  | all.ApartmentComplex
  | all.DrawAction
  | all.TVEpisode
  | all.Person
  | all.NGO
  | all.RejectAction
  | number
  | all.AuthorizeAction
  | all.SheetMusic
  | all.BuyAction
  | all.MediaReviewItem
  | all.FoodEstablishmentReservation
  | all.OnlineBusiness
  | all.ReviewAction
  | all.BoatReservation
  | all.ProfilePage
  | all.EventVenue
  | all.Flight
  | all.LocationFeatureSpecification
  | all.CategoryCode
  | all.PerformanceRole
  | all.ChildrensEvent
  | all.JoinAction
  | all.Comment
  | all.DriveWheelConfigurationValueEnum
  | all.MedicalScholarlyArticle
  | all.Bone
  | all.ChildCare
  | all.SatiricalArticle
  | all.ReviewNewsArticle
  | all.HobbyShop
  | all.DisagreeAction
  | all.Poster
  | all.GatedResidenceCommunity
  | all.RadioSeries
  | all.BusStation
  | all.BusinessEvent
  | all.Organization
  | all.Service
  | all.PlayGameAction
  | all.BusStop
  | all.DoseSchedule
  | all.SendAction
  | all.Movie
  | all.RadioSeason
  | all.MedicalGuideline
  | all.HardwareStore
  | all.BookFormatTypeEnum
  | all.LegislationObject
  | all.TrainReservation
  | all.MedicalConditionStage
  | all.MedicalTherapy
  | all.DiagnosticLab
  | all.HyperToc
  | all.GovernmentOrganization
  | all.RecyclingCenter
  | all.CreativeWorkSeason
  | all.Hotel
  | all.TennisComplex
  | all.LiveBlogPosting
  | all.Cemetery
  | all.BoatTerminal
  | all.HotelRoom
  | all.VisualArtsEvent
  | all.PublicationVolume
  | all.ItemList
  | all.MiddleSchool
  | all.MedicalDevicePurposeEnum
  | all.Drug
  | all.CreativeWorkSeries
  | all.Diet
  | all.ApplyAction
  | all.GovernmentOffice
  | all.Volcano
  | all.RadioChannel
  | all.Observation
  | all.CityHall
  | all.TextObject
  | all.UnRegisterAction
  | all.OccupationalExperienceRequirements
  | all.TouristTrip
  | all.WatchAction
  | all.MobilePhoneStore
  | all.Plumber
  | all.UpdateAction
  | all.MedicalEvidenceLevelEnum
  | all.BodyOfWater
  | all.StructuredValue
  | all.Recipe
  | all.MedicalContraindication
  | all.OpinionNewsArticle
  | all.MovieRentalStore
  | all.Order
  | all.Optician
  | all.ShoeStore
  | all.DislikeAction
  | all.HighSchool
  | all.SuperficialAnatomy
  | all.GameAvailabilityEnumerationEnum
  | all.MedicalCode
  | all.AmpStory
  | all.OfferForPurchase
  | all.DigitalPlatformEnumerationEnum
  | all.DefinedTerm
  | all.EatAction
  | all.Report
  | all.SuspendAction
  | all.PriceComponentTypeEnumerationEnum
  | all.MovieTheater
  | all.MolecularEntity
  | all.ProfessionalService
  | all.Syllabus
  | all.PaymentMethodTypeEnum
  | all.ShippingService
  | all.FinancialService
  | all.MedicalSign
  | all.ContactPointOptionEnum
  | all.PhysiciansOffice
  | all.TipAction
  | all.ActionAccessSpecification
  | all.PaintAction
  | all.OpeningHoursSpecification
  | all.TieAction
  | all.EnergyConsumptionDetails
  | all.HomeAndConstructionBusiness
  | all.PurchaseTypeEnum
  | all.FundingScheme
  | all.CommunicateAction
  | all.Rating
  | all.InteractAction
  | all.DaySpa
  | all.PerformingArtsTheater
  | all.PostOffice
  | all.ResearchProject
  | all.Winery
  | all.EntertainmentBusiness
  | all.CollegeOrUniversity
  | all.DrugPregnancyCategoryEnum
  | all.HealthTopicContent
  | all.MedicalAudience
  | all.TaxiStand
  | all.Airline;
