[package]
name = "schemy"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
indexmap = { version = "2.9.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
