name: CI

on:
  push:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Flake check
        run: nix flake check

      - name: Build Schemy
        run: nix develop -c cargo build --verbose

      - name: Run Schemy Clippy
        run: nix develop -c cargo clippy
